### ISSUE TITLE
Strange Behavior

### ISSUE THREAD

**Issue by buliwyf42** [martinlowinski/php-dyndns#3]
Hello,

i used you system for a long time. 
Now i had to change to another server. And hat to start from scratch.
Unfortunately i now get several errors.
I used all the latest file.

But at the moment i get the following response.

```xml
2017-05-10T20:15:57+02:00 NOTICE [1024]: get current zone records
2017-05-10T20:15:58+02:00 NOTICE [1024]: <?xml version="1.0" encoding="UTF-8" standalone="no"?>
<response>
  <result>
    <data/>
    <msg>
      <text>Diese Zone ist bisher nicht eingetragen.</text>
      <code>EF02020</code>
      <type>error</type>
      <object>
        <type>zone</type>
        <value>xxx.net</value>
      </object>
    </msg>
    <status>
      <code>E0205</code>
      <text>Zoneninformationen konnten nicht ermittelt werden.</text>
      <type>error</type>
      <object>
        <type>zone</type>
        <value>xxx.net</value>
      </object>
    </status>
  </result>
  <stid>20170510-app3-179403</stid>
</response>
```

The Zone is configured and worked for months. 
Perhaps this is the result of the following error.
PHP Fatal error:  Uncaught Error: Call to a member function removeChild() on null in /var/www/clients/client1/web5/web/xxx/update.php:123\nStack trace:\n#0 {main}\n  thrown in /var/www/clients/client1/web5/web/xxx/update.php on line 123

Any Hint or help would be useful. 
I tried it with a single subdomain and 'DOMAIN' and 'DOMAINS'

**Comment by fehrmanns** [comment]
Greetings.

Are you using it for SchlundTech & any wildcards in your define('SYSTEM_NS', '*.schlundtech.de'); ?
I had contact with the support and since I use 'nsa5.schlundtech.de' everything is working fine again. They made some restrictions tight.

**Comment by buliwyf42** [comment]
Nice, i changed it and now it works. 
My old setup didn't even use SYSTEM_NS in the config, and it worked.
I think i can close this here.

**Comment by fehrmanns** [comment]
You're welcome. ;)
